## Exercice 1 

In [1]:
import numpy as np

tb = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(tb)

[0 1 2 3 4 5 6 7 8 9]


## Exercice 2

In [2]:
liste = [3.14, 2.17, 0, 1, 2]

tb2 = np.array(liste)
print(tb2)

[3.14 2.17 0.   1.   2.  ]


## Exercice 3

In [3]:
tb3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tb3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercice 4

In [4]:
tb4= np.array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])
print(tb4)

[[0.56 0.85 0.01 0.42 0.68]
 [0.22 0.37 0.73 0.93 0.39]
 [0.44 0.03 0.87 0.02 0.83]
 [0.78 0.87 0.98 0.8  0.46]]


## Exercice 5

In [5]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array)

[[21 22 23 22 22]
 [20 21 22 23 24]
 [21 22 23 22 22]]


## Exercice 6

In [9]:
tb5 =np.array([0,1,2,3,4,5,6,7,8,9])
# inverser les éléments du tableau
tb6 = np.sort(tb5)[::-1]
print(tb6)


[9 8 7 6 5 4 3 2 1 0]


## Exercice 7

In [11]:
tb7 = np.array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

print(tb7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Exercice 8

In [13]:
sum_tb7 = np.sum(tb7)
mean_tb7 = np.mean(tb7)
print(f"Sum: {sum_tb7}, Average: {mean_tb7}") 

Sum: 4.0, Average: 0.25


## Exercice 9

In [16]:
tb8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,16,17,18,19,20]).reshape(4, 5)
print(tb8)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Exercice 10

In [18]:
tb9 = np.array([0,1,2,3,4,5,6,7,8,9])
tb10 = tb9[tb9 % 2 != 0]
print(tb10)


[1 3 5 7 9]
